version: '3'

services:
  jupyterhub:
    image: jupyterhub/jupyterhub:latest
    container_name: jupyterhub
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:Z  # Changed from docker.sock
      - jupyterhub_data:/data:Z  # Added :Z for SELinux
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    ports:
      - "8000:8000"
    environment:
      - DOCKER_JUPYTER_IMAGE=jupyter/minimal-notebook:latest
    restart: unless-stopped
    networks:
      - jupyterhub-network

networks:
  jupyterhub-network:
    driver: bridge

volumes:
  jupyterhub_data: